server:
  port: 8082
spring:
  application:
    name: product-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  registerWithEureka: true
  fetchRegistry: true